### ISSUE TITLE
Providing methods as an array of strings doesn't trigger retries

### ISSUE THREAD

**Issue by doutatsu** [lostisland/faraday-retry#26]
EDIT:

After investing this in detail, the issue is actually with providing `methods` as an array of strings, which is explained here: https://github.com/lostisland/faraday-retry/issues/26#issuecomment-1555946167

---
I might be understanding the functionality, but I've noticed my requests weren't being retried. My configuration is as follows, where my understanding would be that any of the specified exceptions will be retried. Alternatively, if status code 429 is seen, it will retry the requests using provided interval. Otherwise, it would use a custom interval.

```rb
{"max"=>4.0,
 "methods"=>["get", "post"],
 "interval"=>0.05,
  "exceptions"=>["Faraday::RetriableResponse", "Faraday::TimeoutError", "Faraday::ConnectionFailed"],
  "backoff_factor"=>2.0,
  "retry_statuses"=>[429],
  "interval_randomness"=>0.5
},
```

I've noticed that it was actually not working - when I removed everything but `retry_statuses`, the retries started working as expected again. Can both of these fields not be mixed? Or is it something else overriding the 429 status here?

**Comment by doutatsu** [comment]
Alright, this doesn't seem to be the case - I've tried using only statuses and exceptions. Reading the documentation, I also see that retry_statuses just raises `RetriableResponse`, which gets picked up by `exceptions` array. So it must be something else

**Comment by doutatsu** [comment]
I've found what is the root cause, which feels like a bug - if `methods` are specified as an array of strings, not symbols, nothing gets retried. I was storing my configuration in JSONB, hence why the methods were in string format. If I convert it into symbols, retry logic works as expected, without any changes

**Comment by iMacTia** [comment]
Hi @doutatsu, you're correct, the `methods` option expects an array of symbols as shown in the [README example](https://github.com/lostisland/faraday-retry#specify-which-methods-will-be-retried).
If you pass an array of strings instead, it won't work.

Now, I appreciate we could make `faraday-retry` smarter and deal with both cases, but then we'd need to also deal with uppercase/lowercase strings, which would make the implementation more complicated.
My suggestion would be to do exactly what you did, set the `methods` config to be a list of symbols as intended.

I'm sorry though this is wasn't clear and you had to spend some time figuring this out, so I'd instead be interested to find ways of improving the documentation so that people won't need to go through the same surprise in future.
Would you be able to share some feedback as to where you looked for how to use the `methods` options and where you would have expected we mentioned the list was supposed to be of lowercase symbols?

**Comment by doutatsu** [comment]
I was hoping it would work, considering exceptions allows you to provide both strings and actual classes. To figure it out, I just dug into https://github.com/lostisland/faraday-retry/blob/main/lib/faraday/retry/middleware.rb, but it wasn't obvious until i started removing options and adding them one by one.

The minimum improvement would be to update this:
<img width="536" alt="image" src="https://github.com/lostisland/faraday-retry/assets/4270980/4df33ed3-0ab8-4a39-912e-1067dd687da6">

To actually be explicit about the symbol requirement. Just like you specify it could be anything for exceptions:
<img width="596" alt="image" src="https://github.com/lostisland/faraday-retry/assets/4270980/d6c99fbd-6a3b-40a6-a18b-bddc1af9c8ed">

I would the opposite and say something like: `Methods can only be given as symbols` or something like that.
