### ISSUE TITLE
Retrying on responses with a 429 status code does not work as documented

### ISSUE THREAD

**Issue by andy-gorman** [lostisland/faraday-retry#7]
When specifying `429` as a retry status, it does not use the value provided in the `Retry-After` header as documented. It doesn't retry it at all, as it's rethrown as a `ClientError` before the retry logic is reached, and we need to add `Faraday::ClientError` to the list of exceptions in order to retry properly, which retries more errors than we wish to, and it doesn't use the `Retry-After` header value in this case

**Comment by EricHeitmuller-Gusto** [comment]
@andy-gorman I still see this as an issue - what was the resolution here?

**Comment by iMacTia** [comment]
@EricHeitmuller-Gusto I never replied to this issue because it was immediately closed, but if the exception is being raised as `Faraday::ClientError` that probably means you have the `raise_error` middleware in your stack as well.
Given the way responses go through middleware in your stack, you'll need to ensure the `raise_error` middleware is added to the stack BEFORE the `retry` middleware.

In practice, please make sure your connection init looks like this:
```ruby
conn = Faraday.new(...) do |f|
  ...
  f.response :raise_error
  f.request :retry
  ...
end
```

If this is already the case in your project and you still have this issue, please open a separate issue ticket with more details around your specific setup and I'd be happy to further assist 🙂
